import { builtinModules } from "node:module";
import esbuild from "esbuild";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * Drop Zod Locales Plugin
 *
 * Zod v4 includes ~40 locale files (~150KB) that we don't need.
 * This plugin replaces all non-English locales with empty modules.
 */
const dropZodLocalesPlugin = {
	name: "drop-zod-locales",
	setup(build) {
		// Match zod v4 locale files by absolute path
		build.onLoad(
			{ filter: /zod\/v4\/locales\/[a-z].*\.js$/ },
			(args) => {
				// Keep en.js and index.js
				const filename = path.basename(args.path);
				if (filename === "en.js" || filename === "index.js") {
					return null; // Let esbuild handle normally
				}
				// Return empty module - locales export a default function
				return {
					contents: "export default function() { return {}; }",
					loader: "js",
				};
			}
		);
	},
};

/**
 * Web Worker Plugin
 *
 * This plugin bundles Web Workers (.worker.ts files) into separate bundles
 * that can be instantiated via blob URLs at runtime.
 *
 * Usage in code:
 * - Files named *.worker.ts are automatically processed
 * - The worker code is bundled and stored as a data URL
 * - WorkerClient can instantiate it: new Worker(workerDataUrl)
 */
const webWorkerPlugin = {
	name: "web-worker",
	setup(build) {
		build.onResolve({ filter: /\.worker(\.ts)?$/ }, (args) => {
			// Resolve to absolute path so nested builds can find the entrypoint
			let resolvedPath = path.isAbsolute(args.path)
				? args.path
				: path.join(args.resolveDir, args.path);

			if (!resolvedPath.endsWith(".ts")) {
				resolvedPath += ".ts";
			}

			// Mark as external to handle separately
			return {
				path: resolvedPath,
				namespace: "worker",
				external: false,
			};
		});

		build.onLoad(
			{ filter: /\.worker\.ts$/, namespace: "worker" },
			async (args) => {
				// Bundle worker separately
				const workerCode = await esbuild.build({
					entryPoints: [args.path],
					bundle: true,
					write: false,
					format: "iife",
					target: "es2018",
					minify: prod,
					external: ["obsidian", "electron", ...builtinModules],
					logLevel: "silent",
				});

				if (workerCode.outputFiles && workerCode.outputFiles.length > 0) {
					const code = workerCode.outputFiles[0].text;
					// Return as JavaScript code that creates a blob and URL
					return {
						contents: `
						export default new Blob([${JSON.stringify(code)}], { type: 'application/javascript' });
					`,
						loader: "js",
					};
				}

				return { contents: "" };
			},
		);
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	metafile: true,
	loader: {
		".css": "text",
	},
	plugins: [
		dropZodLocalesPlugin,
		webWorkerPlugin,
		{
			name: "css-plugin",
			setup(build) {
				build.onLoad({ filter: /\.css$/ }, async (args) => {
					const fs = await import("fs");
					const content = fs.readFileSync(args.path, "utf8");
					return {
						contents: `
							const style = document.createElement("style");
							style.textContent = ${JSON.stringify(content)};
							document.head.appendChild(style);
						`,
						loader: "js",
					};
				});
			},
		},
	],
});

if (prod) {
	const result = await context.rebuild();
	// Write metafile for bundle analysis
	if (result.metafile) {
		const fs = await import("fs");
		fs.writeFileSync("meta.json", JSON.stringify(result.metafile));
	}
	process.exit(0);
} else {
	await context.watch();
}
