import { builtinModules } from "node:module";
import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		".css": "text",
	},
	plugins: [
		{
			name: "css-plugin",
			setup(build) {
				build.onLoad({ filter: /\.css$/ }, async (args) => {
					const fs = await import("fs");
					const path = await import("path");
					const content = fs.readFileSync(args.path, "utf8");
					return {
						contents: `
							const style = document.createElement("style");
							style.textContent = ${JSON.stringify(content)};
							document.head.appendChild(style);
						`,
						loader: "js",
					};
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
